spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      # ddl-auto: none

  cloud:
    aws:
      region:
        static: ${AWS_REGION} # ì˜ˆ: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        endpoint: ${AWS_S3_ENDPOINT_URL}
        path-style-access-enabled: true

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}